from pathlib import Path
from datetime import datetime
from typing import Dict, Any

from utils.logger import get_logger

logger = get_logger("Report")


class ReportData:
    """
    Data model for storing report information generated by the Smart File Organizer.

    Attributes
    ----------
    source_folder : str
        The folder that was processed.
    stats : Dict[str, int]
        File statistics per category.
    total_files : int
        Total number of processed files.
    timestamp : str
        Timestamp of when the report was generated.
    """

    def __init__(self, source_folder: str, stats: Dict[str, int]):
        self.source_folder = source_folder
        self.stats = stats
        self.total_files = sum(stats.values())
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        logger.info("ReportData object created")


class ReportFormatter:
    """
    Formatter class responsible for converting ReportData into various output formats.

    Currently supported:
    - TXT (plain text)

    Future formats:
    - JSON (v1.2.0)
    - HTML (v1.3.0)
    - GUI display (v2.0.0)
    """

    @staticmethod
    def to_text(report: ReportData) -> str:
        """
        Convert ReportData into a human-readable text report.

        Parameters
        ----------
        report : ReportData
            The report data object.

        Returns
        -------
        str
            Formatted text report.
        """
        logger.info("Formatting report as TXT")

        lines = [
            "Smart File Organizer Pro - Report",
            "----------------------------------",
            f"Source folder: {report.source_folder}",
            f"Generated at: {report.timestamp}",
            "",
            "File statistics:",
        ]

        for category, count in report.stats.items():
            lines.append(f"- {category}: {count}")

        lines.append("")
        lines.append(f"Total files processed: {report.total_files}")
        lines.append("----------------------------------")

        return "\n".join(lines)


class ReportWriter:
    """
    Writer class responsible for saving reports to disk.

    Attributes
    ----------
    output_dir : Path
        Directory where reports will be saved.
    """

    def __init__(self, output_dir: str = "reports"):
        self.output_dir = Path(output_dir)
        self._ensure_output_directory()

    def _ensure_output_directory(self) -> None:
        """
        Ensure that the output directory exists.
        """
        if not self.output_dir.exists():
            self.output_dir.mkdir(parents=True, exist_ok=True)
            logger.warning(f"Created missing report directory: {self.output_dir}")

    def save_text_report(self, text: str) -> Path:
        """
        Save a text report to the output directory.

        Parameters
        ----------
        text : str
            The formatted text report.

        Returns
        -------
        Path
            Path to the saved report file.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        file_path = self.output_dir / f"report_{timestamp}.txt"

        try:
            with file_path.open("w", encoding="utf-8") as f:
                f.write(text)

            logger.info(f"Report saved successfully: {file_path}")
            return file_path

        except Exception as error:
            logger.error(f"Failed to save report: {error}")
            raise
