from pathlib import Path
from datetime import datetime
from typing import Dict, Any, Optional

from utils.logger import get_logger
from utils.scanner import ScannerData

logger = get_logger("Report")


class ReportData:
    """
    Data model for storing report information generated by the Smart File Organizer.

    Supports both:
    - post-organization statistics (existing behavior)
    - pre-scan analysis results (ScannerData, optional)

    Attributes
    ----------
    source_folder : str
        The folder that was processed.
    stats : Dict[str, int]
        Organizer statistics after file movement.
    total_files : int
        Total number of processed files (post-organization).
    timestamp : str
        Timestamp of when the report was generated.
    scan_data : Optional[ScannerData]
        Pre-scan analysis results (v1.3.0). Optional for backward compatibility.
    """

    def __init__(
        self,
        source_folder: str,
        stats: Dict[str, int],
        scan_data: Optional[ScannerData] = None
    ) -> None:
        self.source_folder = source_folder
        self.stats = stats
        self.total_files = sum(stats.values())
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # NEW in v1.3.0
        self.scan_data = scan_data

        logger.info(
            f"ReportData created for folder '{self.source_folder}' "
            f"with {self.total_files} processed files "
            f"(scan_data={'yes' if scan_data else 'no'})"
        )


class ReportFormatter:
    """
    Formatter class responsible for converting ReportData into various output formats.

    Currently supported:
    - TXT (plain text)

    Future formats:
    - JSON (v1.4.0)
    - HTML (v1.5.0)
    - GUI display (v2.0.0)
    """

    @staticmethod
    def _format_pre_scan_section(report: ReportData) -> str:
        """
        Format the pre-scan (ScannerData) section if available.

        Parameters
        ----------
        report : ReportData

        Returns
        -------
        str
            Formatted pre-scan section or empty string.
        """
        if report.scan_data is None:
            return ""

        sd = report.scan_data

        lines = [
            "",
            "=== Pre-scan summary ===",
            f"Total files: {sd.total_files}",
            f"Total size: {sd.total_size_bytes} bytes",
            "",
            "Category distribution:",
        ]

        for category, count in sd.category_distribution.items():
            lines.append(f"- {category}: {count}")

        if sd.large_files:
            lines.append("")
            lines.append("Large files:")
            for entry in sd.large_files:
                lines.append(
                    f"- {entry['path']} "
                    f"({entry['size_bytes']} bytes, category: {entry['category']})"
                )

        return "\n".join(lines)

    @staticmethod
    def to_text(report: ReportData) -> str:
        """
        Convert ReportData into a human-readable text report.

        Parameters
        ----------
        report : ReportData

        Returns
        -------
        str
            Formatted text report.
        """
        logger.info("Formatting report as TXT")

        lines = [
            "Smart File Organizer Pro - Report",
            "----------------------------------",
            f"Source folder: {report.source_folder}",
            f"Generated at: {report.timestamp}",
        ]

        # NEW: Pre-scan section
        pre_scan_section = ReportFormatter._format_pre_scan_section(report)
        if pre_scan_section:
            lines.append(pre_scan_section)

        # Post-organization summary
        lines.append("")
        lines.append("=== Post-organization summary ===")
        for category, count in report.stats.items():
            lines.append(f"- {category}: {count}")

        lines.append("")
        lines.append(f"Total files processed: {report.total_files}")
        lines.append("----------------------------------")

        return "\n".join(lines)


class ReportWriter:
    """
    Writer class responsible for saving reports to disk.

    Attributes
    ----------
    output_dir : Path
        Directory where reports will be saved.
    """

    def __init__(self, output_dir: str = "reports"):
        self.output_dir = Path(output_dir)
        self._ensure_output_directory()

    def _ensure_output_directory(self) -> None:
        """
        Ensure that the output directory exists.
        """
        if not self.output_dir.exists():
            self.output_dir.mkdir(parents=True, exist_ok=True)
            logger.warning(f"Created missing report directory: {self.output_dir}")

    def save_text_report(self, text: str) -> Path:
        """
        Save a text report to the output directory.

        Parameters
        ----------
        text : str

        Returns
        -------
        Path
            Path to the saved report file.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        file_path = self.output_dir / f"report_{timestamp}.txt"

        try:
            with file_path.open("w", encoding="utf-8") as f:
                f.write(text)

            logger.info(f"Report saved successfully: {file_path}")
            return file_path

        except Exception as error:
            logger.error(f"Failed to save report: {error}")
            raise
