from pathlib import Path
from datetime import datetime
from typing import Dict, Any, Optional

from utils.logger import get_logger
from utils.scanner import ScannerData

logger = get_logger("Report")


class ReportData:
    """
    Data model for storing report information generated by the Smart File Organizer.

    Supports:
    - post-organization statistics (existing behavior)
    - pre-scan analysis results (ScannerData, optional)
    """

    def __init__(
        self,
        source_folder: str,
        stats: Dict[str, int],
        scan_data: Optional[ScannerData] = None
    ) -> None:
        self.source_folder = source_folder
        self.stats = stats
        self.total_files = sum(stats.values())
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.scan_data = scan_data

        logger.info(
            f"ReportData created for folder '{self.source_folder}' "
            f"with {self.total_files} processed files "
            f"(scan_data={'yes' if scan_data else 'no'})"
        )


class ReportFormatter:
    """
    Formatter class responsible for converting ReportData into various output formats.

    Supported:
    - TXT
    - JSON
    - HTML (v1.5.0)
    """

    # -------------------------
    # TXT FORMATTER
    # -------------------------

    @staticmethod
    def _format_pre_scan_section(report: ReportData) -> str:
        if report.scan_data is None:
            return ""

        sd = report.scan_data

        lines = [
            "",
            "=== Pre-scan summary ===",
            f"Total files: {sd.total_files}",
            f"Total size: {sd.total_size_bytes} bytes",
            "",
            "Category distribution:",
        ]

        for category, count in sd.category_distribution.items():
            lines.append(f"- {category}: {count}")

        if sd.large_files:
            lines.append("")
            lines.append("Large files:")
            for entry in sd.large_files:
                lines.append(
                    f"- {entry['path']} "
                    f"({entry['size_bytes']} bytes, category: {entry['category']})"
                )

        return "\n".join(lines)

    @staticmethod
    def to_text(report: ReportData) -> str:
        logger.info("Formatting report as TXT")

        lines = [
            "Smart File Organizer Pro - Report",
            "----------------------------------",
            f"Source folder: {report.source_folder}",
            f"Generated at: {report.timestamp}",
        ]

        pre_scan_section = ReportFormatter._format_pre_scan_section(report)
        if pre_scan_section:
            lines.append(pre_scan_section)

        lines.append("")
        lines.append("=== Post-organization summary ===")
        for category, count in report.stats.items():
            lines.append(f"- {category}: {count}")

        lines.append("")
        lines.append(f"Total files processed: {report.total_files}")
        lines.append("----------------------------------")

        return "\n".join(lines)

    # -------------------------
    # JSON FORMATTER
    # -------------------------

    @staticmethod
    def to_json(report: ReportData) -> Dict[str, Any]:
        logger.info("Formatting report as JSON")

        data: Dict[str, Any] = {
            "source_folder": report.source_folder,
            "generated_at": report.timestamp,
            "post_organization": {
                "categories": report.stats,
                "total_files_processed": report.total_files,
            },
        }

        if report.scan_data is not None:
            sd = report.scan_data
            data["pre_scan"] = {
                "total_files": sd.total_files,
                "total_size_bytes": sd.total_size_bytes,
                "categories": sd.category_distribution,
                "large_files": [
                    {
                        "path": entry["path"],
                        "size_bytes": entry["size_bytes"],
                        "category": entry["category"],
                    }
                    for entry in sd.large_files
                ],
            }

        return data

    # -------------------------
    # HTML FORMATTER (v1.5.0)
    # -------------------------

    @staticmethod
    def to_html(report: ReportData) -> str:
        """
        Convert ReportData into an HTML report string.
        """
        logger.info("Formatting report as HTML")

        # Pre-scan HTML
        pre_scan_html = ""
        if report.scan_data is not None:
            sd = report.scan_data

            # Category distribution table
            category_rows = "".join(
                f"<tr><td>{cat}</td><td>{count}</td></tr>"
                for cat, count in sd.category_distribution.items()
            )

            # Large files list
            large_files_html = ""
            if sd.large_files:
                large_files_html = "<ul>" + "".join(
                    f"<li>{entry['path']} ({entry['size_bytes']} bytes, {entry['category']})</li>"
                    for entry in sd.large_files
                ) + "</ul>"

            pre_scan_html = f"""
            <h2>Pre-scan summary</h2>
            <table border="1" cellpadding="4" cellspacing="0">
                <tr><th>Total files</th><td>{sd.total_files}</td></tr>
                <tr><th>Total size</th><td>{sd.total_size_bytes} bytes</td></tr>
            </table>

            <h3>Category distribution</h3>
            <table border="1" cellpadding="4" cellspacing="0">
                <tr><th>Category</th><th>Count</th></tr>
                {category_rows}
            </table>

            <h3>Large files</h3>
            {large_files_html}
            """

        # Post-organization HTML
        post_rows = "".join(
            f"<tr><td>{cat}</td><td>{count}</td></tr>"
            for cat, count in report.stats.items()
        )

        post_html = f"""
        <h2>Post-organization summary</h2>
        <table border="1" cellpadding="4" cellspacing="0">
            <tr><th>Category</th><th>Count</th></tr>
            {post_rows}
        </table>
        <p><b>Total files processed:</b> {report.total_files}</p>
        """

        # Final HTML document
        html = f"""
        <html>
        <head>
            <meta charset="utf-8">
            <title>Smart File Organizer Pro - Report</title>
        </head>
        <body>
            <h1>Smart File Organizer Pro - Report</h1>
            <p><b>Source folder:</b> {report.source_folder}</p>
            <p><b>Generated at:</b> {report.timestamp}</p>

            {pre_scan_html}
            {post_html}
        </body>
        </html>
        """

        return html.strip()


class ReportWriter:
    """
    Writer class responsible for saving reports to disk.
    """

    def __init__(self, output_dir: str = "reports"):
        self.output_dir = Path(output_dir)
        self._ensure_output_directory()

    def _ensure_output_directory(self) -> None:
        if not self.output_dir.exists():
            self.output_dir.mkdir(parents=True, exist_ok=True)
            logger.warning(f"Created missing report directory: {self.output_dir}")

    def save_text_report(self, text: str) -> Path:
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        file_path = self.output_dir / f"report_{timestamp}.txt"

        try:
            with file_path.open("w", encoding="utf-8") as f:
                f.write(text)

            logger.info(f"Text report saved successfully: {file_path}")
            return file_path

        except Exception as error:
            logger.error(f"Failed to save text report: {error}")
            raise

    def save_json_report(self, data: Dict[str, Any]) -> Path:
        import json

        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        file_path = self.output_dir / f"report_{timestamp}.json"

        try:
            with file_path.open("w", encoding="utf-8") as f:
                json.dump(data, f, indent=2)

            logger.info(f"JSON report saved successfully: {file_path}")
            return file_path

        except Exception as error:
            logger.error(f"Failed to save JSON report: {error}")
            raise

    def save_html_report(self, html: str) -> Path:
        """
        Save an HTML report to the output directory.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        file_path = self.output_dir / f"report_{timestamp}.html"

        try:
            with file_path.open("w", encoding="utf-8") as f:
                f.write(html)

            logger.info(f"HTML report saved successfully: {file_path}")
            return file_path

        except Exception as error:
            logger.error(f"Failed to save HTML report: {error}")
            raise
